services:
  - type: web
    name: patternix-api
    runtime: dotnet
    rootDir: backend/Patternix.Api
    buildCommand: dotnet publish Patternix.Api.csproj -c Release -o out
    startCommand: dotnet out/Patternix.Api.dll
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: LS_CONNECTION_STRING
        sync: false
