services:
  - type: web
    name: patternix-api
    runtime: docker
    dockerContext: backend/Patternix.Api
    dockerfilePath: backend/Patternix.Api/Dockerfile
    autoDeploy: true
    healthCheckPath: /health
    plan: free
    envVars:
      - key: LS_CONNECTION_STRING
        sync: false
